### ISSUE TITLE
Invalid nonce error 400

### ISSUE THREAD

**Issue by tholu** [4ley/nodejs-bitcoin-de-api#7]
I'm getting this error very frequently today:

` {"name":"StatusCodeError","statusCode":400,"message":"400}`

Anybody else seeing this?

**Comment by neuhaus** [comment]
This is not an issue with this software. It is using correct nonces. The issue is on the server side.

What delay do you use in between requests?
If you need to issue requests in rapid succession (less than 1/4 sec or so), consider rotating between multiple credentials as a workaround.

Also complain to bitcoin.de so they get their shit together.

**Comment by tholu** [comment]
This did happen for single requests , so it is most likely a server side issue and bitcoin.de really should get their shit together.
